import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./state/Providers";


export const metadata: Metadata = {
  title: "Workout app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </Providers>
  );
}
