import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./state/Providers";
import RefreshButton from "./components/userDataLoader/RefreshDataButton";
import { UserDataLoader } from "./components/userDataLoader/UserDataLoader";


export const metadata: Metadata = {
  title: "Workout app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <UserDataLoader/>
          <div className="flex w-dvw justify-end absolute bg-transparent"><RefreshButton/></div> { /*temporal nav*/ }
          {children}
        </body>
      </html>
    </Providers>
  );
}
