import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./state/Providers";
import RefreshButton from "./components/userDataLoader/RefreshDataButton";
import { UserDataLoader } from "./components/userDataLoader/UserDataLoader";
import NavbarWrapper from "./components/navbar/NavbarWrapper";


export const metadata: Metadata = {
  title: "Workout app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className="flex flex-col min-h-screen max-w-screen">
          <UserDataLoader/>
          <NavbarWrapper />
          {children}
        </body>
      </html>
    </Providers>
  );
}
